#!/bin/bash

set -e
cleanup() {
    ip netns exec ns0 iptables -t mangle -F PREROUTING
    sleep 1
    rmmod ipt_L4SHENANIGAN_INVERT
    exit_on_err $1
}
trap 'cleanup $LINENO' ERR

insmod $__SRC__/ipt_L4SHENANIGAN_INVERT.ko

ip netns exec ns0 iptables -t mangle -A PREROUTING -j L4SHENANIGAN_INVERT --xmask 255
ip netns exec ns0 iptables-save | expect_has L4SHENANIGAN_INVERT

cleanup
