#ifndef L4SHENANIGANS_UAPI_H
#define L4SHENANIGANS_UAPI_H

#define INVERT_TARGET_NAME "L4SHENANIGAN_INVERT"
#define ENCAP_TARGET_NAME "L4SHENANIGAN_ENCAP"
#define DECAP_TARGET_NAME "L4SHENANIGAN_DECAP"

#define UNUSED(x) (void)(x)

#endif /* L4SHENANIGANS_UAPI_H */
