#ifndef L4SHENANIGANS_UAPI_H
#define L4SHENANIGANS_UAPI_H

#define INVERT_TARGET_NAME "L4SHENANIGAN_INVERT"
#define ENCAP_TARGET_NAME "L4SHENANIGAN_ENCAP"
#define DECAP_TARGET_NAME "L4SHENANIGAN_DECAP"
#define DNAT_TARGET_NAME "L4SHENANIGAN_DNAT"

#define UNUSED(x) (void)(x)

struct l4shenanigan_invert_info {
  char xmask;
};

#endif /* L4SHENANIGANS_UAPI_H */
