#!/bin/bash

set -e

cleanup() {
  kill $iperf_server || :
  exit_on_err $1
}

trap 'cleanup $LINENO' ERR

ip netns exec ns1 iperf3 -s &
iperf_server=$!
sleep 0.5
ip netns exec ns0 iperf3 -uc 192.168.1.2 -t 3

cleanup
