#!/bin/bash

set -e
cleanup() {
    ip netns exec ns0 iptables -t mangle -F PREROUTING
    sleep 1
    rmmod ipt_L4SHENANIGAN_ENCAP
    rmmod ipt_L4SHENANIGAN_DECAP
    exit_on_err $1
}
trap 'cleanup $LINENO' ERR

insmod $__SRC__/ipt_L4SHENANIGAN_ENCAP.ko
insmod $__SRC__/ipt_L4SHENANIGAN_DECAP.ko

ip netns exec ns0 iptables -t mangle -A PREROUTING -j L4SHENANIGAN_ENCAP
ip netns exec ns0 iptables -t mangle -A POSTROUTING -j L4SHENANIGAN_DECAP
ip netns exec ns0 iptables-save | expect_has L4SHENANIGAN_ENCAP
ip netns exec ns0 iptables-save | expect_has L4SHENANIGAN_DECAP

ip netns exec ns0 iptables -t mangle -F PREROUTING
ip netns exec ns0 iptables -t mangle -F POSTROUTING

cleanup
