#!/bin/bash
set -e
set -x

#     ENCAP   DECAP  DNAT
#     ns0    |    ns1    |    ns2
#         v0 | v1     v2 | v3
#        1.1   1.2   2.1   2.2

ip netns del ns0 || :
ip netns del ns1 || :
ip netns del ns2 || :

ip netns add ns0
ip netns add ns1
ip netns add ns2

ip netns exec ns1 sysctl net.ipv4.conf.all.forwarding=1

ip l add v0 type veth peer name v1
ip l set v0 netns ns0
ip l set v1 netns ns1

ip l add v2 type veth peer name v3
ip l set v2 netns ns1
ip l set v3 netns ns2

ip netns exec ns0 ip l set lo up
ip netns exec ns0 ip l set v0 up
ip netns exec ns0 ip a add 192.168.1.1/24 dev v0
ip netns exec ns0 ip r add 192.168.2.0/24 via 192.168.1.2

ip netns exec ns1 ip l set lo up
ip netns exec ns1 ip l set v1 up
ip netns exec ns1 ip l set v2 up
ip netns exec ns1 ip a add 192.168.1.2/24 dev v1
ip netns exec ns1 ip a add 192.168.2.1/24 dev v2

ip netns exec ns2 ip l set lo up
ip netns exec ns2 ip l set v3 up
ip netns exec ns2 ip a add 192.168.2.2/24 dev v3
ip netns exec ns2 ip r add 192.168.1.0/24 via 192.168.2.1

ip netns exec ns0 ethtool --offload v0 rx off tx off
ip netns exec ns0 ethtool -K v0 gso off
ip netns exec ns1 ethtool --offload v1 rx off tx off
ip netns exec ns1 ethtool -K v1 gso off
ip netns exec ns1 ethtool --offload v2 rx off tx off
ip netns exec ns1 ethtool -K v2 gso off
ip netns exec ns2 ethtool --offload v3 rx off tx off
ip netns exec ns2 ethtool -K v3 gso off

rmmod ipt_L4SHENANIGAN_ENCAP || :
rmmod ipt_L4SHENANIGAN_DECAP || :
rmmod ipt_L4SHENANIGAN_DNAT || :
