#!/bin/bash

set -e
set -x

cleanup() {
    ip netns exec ns0 iptables -t mangle -F PREROUTING
    sleep 1
    rmmod ipt_L4SHENANIGAN_INVERT
    rmmod ipt_L4SHENANIGAN_ENCAP
    rmmod ipt_L4SHENANIGAN_DECAP
    rmmod ipt_L4SHENANIGAN_DNAT
    exit_on_err $1
}
trap 'cleanup $LINENO' ERR

modprobe nf_nat

insmod $__SRC__/ipt_L4SHENANIGAN_INVERT.ko
insmod $__SRC__/ipt_L4SHENANIGAN_ENCAP.ko
insmod $__SRC__/ipt_L4SHENANIGAN_DECAP.ko
insmod $__SRC__/ipt_L4SHENANIGAN_DNAT.ko

ip netns exec ns0 iptables -t mangle -A PREROUTING -j L4SHENANIGAN_INVERT --xmask 255
ip netns exec ns0 iptables -t mangle -A PREROUTING -j L4SHENANIGAN_ENCAP
ip netns exec ns0 iptables -t mangle -A POSTROUTING -j L4SHENANIGAN_DECAP
ip netns exec ns0 iptables -t nat -A PREROUTING -j L4SHENANIGAN_DNAT
ip netns exec ns0 iptables-save | expect_has L4SHENANIGAN_INVERT
ip netns exec ns0 iptables-save | expect_has L4SHENANIGAN_ENCAP
ip netns exec ns0 iptables-save | expect_has L4SHENANIGAN_DECAP
ip netns exec ns0 iptables-save | expect_has L4SHENANIGAN_DNAT

ip netns exec ns0 ping -W 1 -c 3 192.168.2.2 2>&1 | expect_has '3 received'

ip netns exec ns0 iptables -t mangle -F PREROUTING
ip netns exec ns0 iptables -t mangle -F POSTROUTING
ip netns exec ns0 iptables -t nat -F PREROUTING

cleanup
